clear all;
close all;
clc;
% out = Wrapper(  '..\Images\Set1\1.jpg','..\Images\Set1\2.jpg','..\Images\Set1\3.jpg');
% out = Wrapper(  '..\Images\Set2\1.jpg','..\Images\Set2\2.jpg','..\Images\Set2\3.jpg');
out = Wrapper(  ...
                '..\..\Images\Set3\1.jpg','..\..\Images\Set3\2.jpg','..\..\Images\Set3\3.jpg', ...
                '..\..\Images\Set3\4.jpg','..\..\Images\Set3\5.jpg','..\..\Images\Set3\6.jpg', ...
                '..\..\Images\Set3\7.jpg','..\..\Images\Set3\8.jpg' ...
                );

% out = Wrapper(  ...
%                 '..\Images\TestSet_P1\TestSet1\1.jpg','..\Images\TestSet_P1\TestSet1\2.jpg','..\Images\TestSet_P1\TestSet1\3.jpg', ...
%                 '..\Images\TestSet_P1\TestSet1\4.jpg' ...
%                 );

% out = Wrapper(  ...
%                 '..\Images\TestSet_P1\TestSet3\1.jpg','..\Images\TestSet_P1\TestSet3\2.jpg','..\Images\TestSet_P1\TestSet3\3.jpg' ...
%                 );

